# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  AppName: UE4_azure_github_mirror
  OutputDir: _buildOutput
  TmpRepoDir: _repo
  GitHubPath: github.com/udemegane/UE426_azuretest_mirror.git
  Github_Username: udemegane
  Github_email: cappuccino1204.ck@gmail.com
pool:
  vmImage: 'ubuntu-latest'
trigger:
- master
steps:   
- script: |
    git config --global user.name udemegane
    git config --global user.email cappuccino1204.ck@gmail.com
  displayName: 'Set git config'

- script: |
    cd /tmp && rm -rf /tmp/$(TmpRepoDir)
  displayName: 'Reset tmp folder'

- task: CopyFiles@2
  inputs:
    contents: '$(Build.SourcesDirectory)/AzureTest_cpp/Source/**'
    targetFolder: /tmp/$(TmpRepoDir)

- script: |
    cd /tmp/$(TmpRepoDir)
    git add -A
          if ! (git diff --quiet && git diff --staged --quiet); then
            git commit -m "Add: changes ($GITHUB_SHA)" 
          fi
    git push https://udemegane:$(Github_Token)@github.com/udemegane/UE426_azuretest_mirror.git
  displayName: 'Copy to Github'

