# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  AppName: UE4_azure_github_mirror
  OutputDir: _buildOutput
  TmpRepoDir: _repo
  GitHubPath: github.com/udemegane/UE426_azuretest_mirror.git
  Github_Username: udemegane
  Github_email: cappuccino1204.ck@gmail.com
pool:
  vmImage: 'ubuntu-latest'
trigger:
- master
steps:   
- task: CopyFiles@2
  inputs:
    contents: '$(Build.SourcesDirectory)/AzureTest_cpp/Source/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs    
- script: |
    cd /tmp && rm -rf /tmp/$(TmpRepoDir)
    git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" clone --mirror $(Build.Repository.Uri) $(TmpRepoDir)
    
  displayName: 'Move to tmpfolder '
- script: |
    git config --global user.name udemegane
    git config --global user.email cappuccino1204.ck@gmail.com
  displayName: 'Set git config'

- script: |
    mkdir ~/.ssh 
    chmod 700 ~/.ssh
    echo $(sshkey-github) > ~/.ssh/id_ecdsa
    chmod 600 ~/.ssh/id_ecdsa
  displayName: 'Set Key'

- script: |
    cd /tmp/$(TmpRepoDir)
    git init
    git add -A
    git commit -m "Mirror Source code from Azure repos"  
    git push origin main 
  displayName: 'Copy to Github'

